### ISSUE TITLE
Set distribution variables with `include_vars`

### ISSUE THREAD

**Issue by benwebber** [devops-coop/ansible-haproxy#79]
Use this standard pattern instead of `set_fact`:

```yaml
- name: Load a variable file based on the OS type, or a default if not found. Using free-form to specify the file.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml
```
